APP_NAME: "ML"
AUTHORIZATION: "Authorization"
MESH_URL: "http://localhost:3011"
BACKEND_URL: "http://localhost:3100"
REMIGPT_URL: "http://localhost:3100"
BERTOPIC_URL: "http://localhost:5000"
BERTOPIC_API_KEY: "API_KEY"
